package com.ncc.neon.state

import groovy.transform.EqualsAndHashCode
import groovy.transform.Immutable



/**
 * Contains an id generated by the client and the state of the widget, which is typically
 * a json string.
 */

@EqualsAndHashCode(includes = "clientId")
@Immutable
class WidgetState{

    String clientId
    String state

}
