ruleset {
    AbstractClassName 
    AbstractClassWithoutAbstractMethod 
    AbstractClassWithPublicConstructor 
    AddEmptyString 
    AssertWithinFinallyBlock 
    AssignCollectionSort 
    AssignCollectionUnique 
    AssignmentInConditional 
    BigDecimalInstantiation 
    BitwiseOperatorInConditional 
    BooleanGetBoolean 
    BooleanMethodReturnsNull 
    BrokenNullCheck 
    BrokenOddnessCheck 
    BuilderMethodWithSideEffects {
        methodNameRegex = 'build.*'
    }
    BusyWait 
    CatchArrayIndexOutOfBoundsException 
    CatchError 
    CatchException 
    CatchIllegalMonitorStateException 
    CatchIndexOutOfBoundsException 
    CatchNullPointerException 
    CatchRuntimeException 
    CatchThrowable 
    ChainedTest 
    ClassForName 
    ClassName 
    ClassNameSameAsFilename 
    CloneableWithoutClone 
    ClosureAsLastMethodParameter 
    CollectAllIsDeprecated 
    CompareToWithoutComparable 
    ComparisonOfTwoConstants 
    ComparisonWithSelf 
    ConfusingClassNamedException 
    ConfusingMethodName 
    ConfusingMultipleReturns 
    ConsecutiveLiteralAppends 
    ConsecutiveStringConcatenation 
    ConstantAssertExpression 
    ConstantIfExpression 
    ConstantsOnlyInterface 
    ConstantTernaryExpression 
    CoupledTestCase 
    DeadCode 
    DoubleCheckedLocking 
    DoubleNegative 
    DuplicateCaseStatement 
    DuplicateImport 
    DuplicateListLiteral 
    DuplicateMapKey 
    DuplicateMapLiteral 
    DuplicateSetValue 
    ElseBlockBraces 
    EmptyCatchBlock 
    EmptyClass 
    EmptyElseBlock 
    EmptyFinallyBlock 
    EmptyForStatement 
    EmptyIfStatement 
    EmptyInstanceInitializer 
    EmptyMethod 
    EmptyMethodInAbstractClass 
    EmptyStaticInitializer 
    EmptySwitchStatement 
    EmptySynchronizedStatement 
    EmptyTryBlock 
    EmptyWhileStatement 
    EnumCustomSerializationIgnored 
    EqualsAndHashCode
    EqualsOverloaded 
    ExceptionExtendsError 
    ExceptionNotThrown 
    ExplicitArrayListInstantiation 
    ExplicitCallToAndMethod 
    ExplicitCallToCompareToMethod 
    ExplicitCallToDivMethod 
    ExplicitCallToEqualsMethod 
    ExplicitCallToGetAtMethod 
    ExplicitCallToLeftShiftMethod 
    ExplicitCallToMinusMethod 
    ExplicitCallToModMethod 
    ExplicitCallToMultiplyMethod 
    ExplicitCallToOrMethod 
    ExplicitCallToPlusMethod 
    ExplicitCallToPowerMethod 
    ExplicitCallToRightShiftMethod 
    ExplicitCallToXorMethod 
    ExplicitGarbageCollection 
    ExplicitHashMapInstantiation 
    ExplicitHashSetInstantiation 
    ExplicitLinkedHashMapInstantiation 
    ExplicitLinkedListInstantiation 
    ExplicitStackInstantiation 
    ExplicitTreeSetInstantiation 
    FieldName 
    FinalClassWithProtectedMember 
    ForLoopShouldBeWhileLoop 
    ForStatementBraces 
    GetterMethodCouldBeProperty 
    GroovyLangImmutable 
    GStringAsMapKey 
    GStringExpressionWithinString 
    HardCodedWindowsFileSeparator 
    HardCodedWindowsRootDirectory 
    HashtableIsObsolete 
    IfStatementBraces 
    ImplementationAsType 
    ImportFromSamePackage 
    ImportFromSunPackages 
    InconsistentPropertyLocking 
    InconsistentPropertySynchronization 
    InsecureRandom 
    IntegerGetInteger 
    InterfaceName 
    JavaIoPackageAccess 
    JUnitAssertAlwaysFails 
    JUnitAssertAlwaysSucceeds 
    JUnitFailWithoutMessage 
    JUnitLostTest 
    JUnitPublicField 
    JUnitPublicNonTestMethod 
    JUnitSetUpCallsSuper 
    JUnitStyleAssertions 
    JUnitTearDownCallsSuper 
    JUnitUnnecessarySetUp 
    JUnitUnnecessaryTearDown 
    JUnitUnnecessaryThrowsException 
    LoggerForDifferentClass 
    LoggerWithWrongModifiers 
    LoggingSwallowsStacktrace 
    LongLiteralWithLowerCaseL
    MethodName {
        regex = '[a-z].*'
    }
    MethodSize {
        maxLines = 20
    }
    MissingNewInThrowStatement 
    MultipleLoggers 
    NestedSynchronization 
    NonFinalPublicField 
    NonFinalSubclassOfSensitiveInterface 
    ObjectFinalize 
    ObjectOverrideMisspelledMethodName 
    PackageName 
    ParameterName 
    ParameterReassignment 
    Println 
    PrintStackTrace 
    PrivateFieldCouldBeFinal 
    PropertyName
    PublicFinalizeMethod 
    PublicInstanceField 
    RandomDoubleCoercedToZero 
    RemoveAllOnSelf 
    ReturnFromFinallyBlock 
    ReturnNullFromCatchBlock 
    ReturnsNullInsteadOfEmptyArray 
    ReturnsNullInsteadOfEmptyCollection 
    SerializableClassMustDefineSerialVersionUID 
    SerialPersistentFields 
    SerialVersionUID 
    SimpleDateFormatMissingLocale 
    SpockIgnoreRestUsed 
    StatelessSingleton 
    StaticCalendarField 
    StaticConnection 
    StaticDateFormatField 
    StaticMatcherField 
    StaticSimpleDateFormatField 
    SwallowThreadDeath 
    SynchronizedMethod 
    SynchronizedOnBoxedPrimitive 
    SynchronizedOnGetClass 
    SynchronizedOnReentrantLock 
    SynchronizedOnString 
    SynchronizedOnThis 
    SynchronizedReadObjectMethod 
    SystemErrPrint 
    SystemExit 
    SystemOutPrint 
    SystemRunFinalizersOnExit 
    TernaryCouldBeElvis 
    ThisReferenceEscapesConstructor 
    ThreadGroup 
    ThreadLocalNotStaticFinal 
    ThreadYield 
    ThrowException 
    ThrowExceptionFromFinallyBlock 
    ThrowNullPointerException 
    ThrowRuntimeException 
    ThrowThrowable 
    UnnecessaryBigDecimalInstantiation 
    UnnecessaryBigIntegerInstantiation 
    UnnecessaryBooleanExpression 
    UnnecessaryBooleanInstantiation 
    UnnecessaryCallForLastElement 
    UnnecessaryCallToSubstring 
    UnnecessaryCatchBlock 
    UnnecessaryCollectionCall 
    UnnecessaryConstructor 
    UnnecessaryDotClass 
    UnnecessaryDoubleInstantiation 
    UnnecessaryElseStatement 
    UnnecessaryFail 
    UnnecessaryFinalOnPrivateMethod 
    UnnecessaryFloatInstantiation 
    UnnecessaryGroovyImport 
    UnnecessaryIfStatement 
    UnnecessaryInstanceOfCheck 
    UnnecessaryInstantiationToGetClass 
    UnnecessaryIntegerInstantiation 
    UnnecessaryLongInstantiation 
    UnnecessaryModOne 
    UnnecessaryNullCheck 
    UnnecessaryNullCheckBeforeInstanceOf 
    UnnecessaryObjectReferences 
    UnnecessaryOverridingMethod 
    UnnecessaryPackageReference 
    UnnecessaryParenthesesForMethodCallWithClosure 
    UnnecessarySelfAssignment 
    UnnecessarySemicolon 
    UnnecessaryStringInstantiation 
    UnnecessaryTernaryExpression 
    UnnecessaryTransientModifier 
    UnsafeArrayDeclaration 
    UnusedArray 
    UnusedImport 
    UnusedMethodParameter 
    UnusedObject 
    UnusedPrivateField 
    UnusedPrivateMethod 
    UnusedPrivateMethodParameter 
    UnusedVariable 
    UseAssertEqualsInsteadOfAssertTrue 
    UseAssertFalseInsteadOfNegation 
    UseAssertNullInsteadOfAssertEquals 
    UseAssertSameInsteadOfAssertTrue 
    UseAssertTrueInsteadOfAssertEquals 
    UseAssertTrueInsteadOfNegation 
    UseCollectMany 
    UseCollectNested 
    UseOfNotifyMethod 
    VariableName 
    VectorIsObsolete 
    VolatileArrayField 
    VolatileLongOrDoubleField 
    WaitOutsideOfWhileLoop 
    WhileStatementBraces 
}
